---
title: CV SETIADI TRANS JAYA
timezone: UTC
collections:
  pages:
    title: Page
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
future: true
baseurl: ''
url: https://setiaditrans.com
disqus:
  shortname: setiadi-trans
google_analytics: 
theme: minima
plugins:
- jekyll-sitemap
- jekyll-paginate
include:
- _uploads
- ads.txt
- robot.txt
- favicon.ico
paginate: 4
