---
title: CV SETIADI TRANS
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: ''
url: https://setiadi-trans.github.io
disqus:
  shortname: setiadi-trans
google_analytics: 
theme: minima
plugins:
- jekyll-sitemap
- jekyll-paginate
include:
- _uploads
- ads.txt
- robot.txt
paginate: 4
